# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# needed for GitHub codespaces
export SHELL=/bin/zsh

# path
PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
PATH="$HOME/go/bin:$PATH"
PATH=$HOME/bin:$PATH
export PATH

# go
export GOPATH="$HOME/go"

# misc
export EDITOR='nvim'
export GIT_OPEN='nvim'
export GITHUB_USER=nodo
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# Alias and helpers
alias k=kubectl
alias ls="ls --color=auto"
alias vim=nvim
alias dotfiles="cd /workspaces/.codespaces/.persistedshare/dotfiles"

eval "$(starship init zsh)"
