# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# needed for GitHub codespaces
export SHELL=/bin/zsh

# Homebrew (works on macOS and Linux)
if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
elif [[ -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# path
PATH="$HOME/go/bin:$PATH"
PATH=$HOME/bin:$PATH

# export path only once
export PATH

# go
export GOPATH="$HOME/go"

# misc
export EDITOR='nvim'
export GIT_OPEN='nvim'
export GITHUB_USER=nodo
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# Alias and helpers
alias k=kubectl
alias vim=nvim
alias dotfiles="cd /workspaces/.codespaces/.persistedshare/dotfiles"

# ls alias (cross-platform)
if [[ "$(uname)" == "Darwin" ]]; then
  alias ls="ls -G"
else
  alias ls="ls --color=auto"
fi

eval "$(starship init zsh)"
