#!/bin/bash

set -euo pipefail
set -x

# install packages
sudo apt-get update && sudo apt-get install -y build-essential

# link dotfiles
files=(
	"ripgreprc"
	"gitconfig"
	"tmux.conf"
	"zshrc"
)
for file in ${files[@]}; do
	ln -fs ${PWD}/config/${file} ${HOME}/.${file}
done

# linuxbrew
NONINTERACTIVE=1 bash <(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
HOMEBREW_INSTALL_FROM_API=true brew bundle install --file ${PWD}/Brewfile

# starship
mkdir -p ${HOME}/.config
starship preset pure-preset -o ${HOME}/.config/starship.toml

# tmux (installing tpm)
mkdir -p ${HOME}/.tmux/plugins
rm -rf ${HOME}/.tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm

TMUX_BIN=/home/linuxbrew/.linuxbrew/bin/tmux
${TMUX_BIN} start-server
${TMUX_BIN} new-session -d
${HOME}/.tmux/plugins/tpm/scripts/install_plugins.sh
${TMUX_BIN} kill-server

# zsh
rm -rf ${HOME}/.oh-my-zsh
sh <(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --keep-zshrc
sudo chsh -s /bin/zsh ${USER}

# neovim
ln -fs ${PWD}/nvim ${HOME}/.config/nvim

# install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

export NVM_DIR="/usr/local/share/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm install node
nvm use node
npm install -g @github/copilot@latest
