#!/bin/bash

set -euo pipefail

# install packages
sudo apt-get update
sudo apt-get install -y \
	build-essential \
	curl \
	zsh

# link dotfiles
files=(
	"ripgreprc"
	"gitconfig"
	"tmux.conf"
	"zshrc"
)
for file in ${files[@]}; do
	ln -fs ${PWD}/config/${file} ${HOME}/.${file}
done

# starship
curl -sS https://starship.rs/install.sh -o /tmp/install-starship.sh
sudo sh /tmp/install-starship.sh -y
mkdir -p ${HOME}/.config
starship preset pure-preset -o ${HOME}/.config/starship.toml

# zsh
curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -o /tmp/install-ohmyzsh.sh
sudo sh /tmp/install-ohmyzsh.sh --keep-zshrc
