#!/bin/bash

set -e

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "codespace.*/bin/zsh" /etc/passwd
then
  WHOAMI=`whoami`
  sudo chsh -s /bin/zsh $WHOAMI
fi

# install linuxbrew suggested packages
sudo apt-get update
sudo apt-get install -y build-essential
