require "nodo.options"
require "nodo.keymaps"
require "nodo.plugins"
require "nodo.colorscheme"
-- require "nodo.cmp"
require "nodo.lsp"
require "nodo.telescope"
require "nodo.gitsigns"
require "nodo.treesitter"
require "nodo.comment"
require "nodo.nvim-tree"
-- require "nodo.bufferline"
require "nodo.lualine"
-- require "nodo.impatient"
-- require "nodo.indentline"
-- require "nodo.whichkey"
-- require "nodo.autocommands"
